### ISSUE TITLE
Can this get a profile?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/listcognatebenchmark#1]

**Comment by XachaB** [comment]
It looks like this dataset is planned to go into lexicore, which makes creating a profile more urgent. In particular, I find the following phonemes which look abnormal:

- t͡l: 12 occurences, exs: a t͡l i r; m ɪː c ɪ t͡l; f ʏ t͡l ʏ r
- ɛʰ: 4 occurences, exs: t r ɛʰ k a; ɛʰ c ɪ; t r ɛʰ k a
- ɔyə: 2 occurences, exs: f ɔyə r; f ɔyə r
-  aɪə: 3 occurences, exs: f aɪə r; f aɪə; f aɪə r
- t͡n: 10 occurences, exs: k r ai t͡n; h ɔ r t͡n; ei t͡n
- ouʰ: 4 occurences, exs: n ouʰ t; kʰ r i ŋ l ouʰ t ʏ r; n ouʰ t
-  aʰ: 2 occurences, exs: v aʰ t n̥; v aʰ t n̥
-  ⁰⁴: 60 occurences, exs: tʰ a j ²¹³ i ŋ ⁰⁴; l o ⁴⁵ pʰ o ⁰⁴ ɕ y ⁴⁵; m ɑ ⁴⁵ ʨʰ j ɔ ʔ ⁰⁴ ʦ ɿ ⁰⁴
-  ⁰²: 45 occurences, exs: ȵ i ʔ ⁵ tʰ u ⁰²; s j ɑ ŋ ⁴² ʦ ɿ ⁰²; t ɑ ²¹³ f ɔ ʔ ⁵ s ɛ n ⁰²

**Comment by LinguList** [comment]
@xachab, you can leave this to me to fiddle with the cases, as this is a
dataset that was originally compiled by myself, and I wrote the first
code for lexibank long time ago.

**Comment by XachaB** [comment]
Thanks !
